apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-ing-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-app
  template:
    metadata:
      labels:
        app: back-app
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        ports:
        - containerPort: 80
