apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-ing-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ing-app
  template:
    metadata:
      labels:
        app: ing-app
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
